version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: app_laravel
    ports:
      - "8000:8000"
      - "2019:2019"
    volumes:
      - ./laravel-project:/app/
      - ~/.aws:/root/.aws
    environment:
      - AWS_PROFILE=admin